version: '3.7'

volumes:
    libmariadb:
        driver: local

services:
    slim:
        image: php:8-alpine
        restart: always
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
    db_mysql:
        image: mariadb:latest
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: "password"
            MARIADB_DATABASE: "slim"
            MARIADB_AUTO_UPGRADE: "true"
        volumes:
            - libmariadb:/var/lib/mysql
            - ./schema:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
